_BASE_: ../oneformer_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "FasterViTransformer"
  FASTERVIT:
    DIM: 64
    IN_DIM: 64
    DEPTHS: [3, 3, 12, 5]
    NUM_HEADS: [2, 4, 8, 16]
    WINDOW_SIZE: [7, 7, 14, 14]

  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  ONE_FORMER:
    NUM_OBJECT_QUERIES: 150
SOLVER:
  STEPS: (655556, 735184)
  MAX_ITER: 737500
  AMP:
    ENABLED: False
TEST:
  DETECTIONS_PER_IMAGE: 150
